#!/usr/bin/env bun
/**
 * Version stamp script — generates packages/shared/src/build-info.generated.ts.
 *
 * Reads git SHA, branch, and timestamp. Writes a TypeScript module that exports
 * BUILD_INFO. Supports env var overrides for Docker builds where .git is unavailable.
 *
 * Priority for SHA resolution:
 *   1. GIT_SHA env var (explicit override, used in Docker build args)
 *   2. RAILWAY_GIT_COMMIT_SHA env var (Railway auto-sets this during builds)
 *   3. `git rev-parse HEAD` (local dev / CI)
 *   4. "unknown" (final fallback)
 *
 * Usage:
 *   bun run scripts/stamp-version.ts                     # local dev
 *   GIT_SHA=abc123 bun run scripts/stamp-version.ts      # Docker build
 */
import { join } from "node:path";

const OUTPUT_PATH = join(import.meta.dir, "..", "packages", "shared", "src", "build-info.generated.ts");

function exec(cmd: string[]): string {
  try {
    const result = Bun.spawnSync(cmd, { stdout: "pipe", stderr: "pipe" });
    return result.stdout.toString().trim();
  } catch {
    return "";
  }
}

// Resolve git metadata with fallback chain
const commitSha =
  process.env.GIT_SHA ||
  process.env.RAILWAY_GIT_COMMIT_SHA ||
  exec(["git", "rev-parse", "HEAD"]) ||
  "unknown";

const commitShort =
  process.env.GIT_SHORT ||
  (commitSha !== "unknown" && commitSha.length >= 7 ? commitSha.slice(0, 7) : commitSha) ||
  "unknown";

const branch =
  process.env.GIT_BRANCH ||
  process.env.RAILWAY_GIT_BRANCH ||
  exec(["git", "rev-parse", "--abbrev-ref", "HEAD"]) ||
  "unknown";

const buildDate = process.env.BUILD_DATE || new Date().toISOString();

const content = `// AUTO-GENERATED by scripts/stamp-version.ts — do not edit
export const BUILD_INFO = {
  commitSha: ${JSON.stringify(commitSha)},
  commitShort: ${JSON.stringify(commitShort)},
  buildDate: ${JSON.stringify(buildDate)},
  branch: ${JSON.stringify(branch)},
} as const;
`;

await Bun.write(OUTPUT_PATH, content);
console.log(`Stamped: ${commitShort} (${branch}) at ${buildDate}`);
